# Generated by Django 2.1.7 on 2019-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_city', models.CharField(max_length=25)),
                ('days', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
