# Generated by Django 2.1.7 on 2019-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='current',
            name='city_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='days',
            field=models.IntegerField(),
        ),
    ]
