# Generated by Django 2.1.7 on 2019-03-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_auto_20190318_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='forecast_city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='days',
        ),
    ]
