# Generated by Django 2.1.7 on 2019-03-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_auto_20190322_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Age',
        ),
    ]
